config/routes.rb
Rails.application.routes.draw do
  # get 'user/index'
  devise_for :users
  # get 'events/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"

  # get 'user_path(:id)' => '/users'

  # get 'signup' => 'users#new', as: 'signup'
  # get 'login' => 'devise/sessions#new', as: 'login'
  get 'logout' => 'devise/sessions#destroy'

  resources :user, only: [:index,:show]
  resources :events
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
    has_many :event_attendees, foreign_key: 'attended_event_id', dependent: :destroy
    has_many :attendees, :through => :event_attendees, :source => :attendee
    # has_many :attendee, :through => :event_attendees
    validates :name, :location, :date, presence: true
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, class_name: "Event"
  has_many :event_attendees, foreign_key: "attendee_id"
  has_many :attended_events, :through => :event_attendees, :source => :attended_event
  validates :name, :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:password, :email) }
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
        # devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
    end
    def logged_in?
        !current_user.nil?
    end

    def logged_in_user
        unless logged_in?
            store_location
            flash[:danger] = "Please log in."
            redirect_to login_url 
        end	
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :logged_in_user, only: [:create, :destroy]
  
  def index
    @events = Event.all 
    @past_events = Event.where("date < ?", Date.today)
    @upcoming_events =  Event.where("date > ?", Date.today)
  end


  def new
    @events = Event.new 
  end
  
  def show 
    @event = Event.find(params[:id])
  end

  def create 
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event was saved!"
      render 'show'
    else
      render 'new'
    end
  end

  def update
    flash[:notice] = "Updated!"
    @event = Event.find(params[:id])
    if attendee_checked?
      add_attendees
    end
    redirect_to '/events/new'
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted"
    redirect_to events_url
	end

  private
    def event_params
      params.require(:event).permit(:name,:location,:date, :description)
    end

    def attendee_checked?
      params[:event][:attendees] == '1'
    end

    def add_attendees
      @event = Event.find(params[:id])
      if current_user.attended_event_ids.include?(@event.id)
        flash[:notice] = "You have already added this event."
      else 
        @event.attendees << current_user
      end
    end
    
  end

app/controllers/user_controller.rb
# require 'session_helper'

class UserController < ApplicationController
  before_action :authenticate_user!
  before_action :logged_in_user, only: [:index, :destroy]
  # before_filter :authenticate_user!
  def index
    @user = User.all 
    @current_user = current_user
  end

  def create 
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome"
      redirect_to root_path
    else
      flash[:alert] = "failed to save"
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events =  @user.events
    @attended_events  = @user.attended_events
    # @upcoming_created_events = upcoming_created_events @user
    # @past_created_events = past_created_events @user
    # @upcoming_attended_events = upcoming_attended_events @user 
    # @past_attended_events = past_attended_events @user
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end 

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<div class = "container">
    <h1>Welcome to Private Event!</h1>
    <ul>
        <% @events.each do |event| %>
            <div class="row" id="event-row">
                <p class="event-title"><%= link_to event.name, event %></p> 
            </div>
        <% end %>
        <div class="button"><%= link_to 'Create New Event', new_event_path%></div>
        <div class="row">
        <h3>Past Events</h3>
        <% @past_events.each do |event| %>
            <div class="row" id="event-row">
                <p class="event-title"><%= link_to event.name, event %></p> 
            </div>
        <% end %>
    </div>
    <div class="row">
        <h3>Upcoming Events</h3>
        <% @upcoming_events.each do |event| %>
            <div class="row" id="event-row">
                <p class="event-title"><%= link_to event.name, event %></p> 
            </div>
        <% end %>
    </div>
    </ul>
    
</div>

app/views/events/new.html.erb
<div class="container">
<h1>New Event</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for Event.create do |f| %>
			<%# <%= render 'shared/error_messages', object: f.object %>  %>

            <div class="input-field">
                <%= f.label :name %>
                <%= f.text_field :name %>
            </div>	
            
            <div class="input-field">	
                <%= f.label :location %>
                <%= f.text_field :location %>
            </div>	

            <span class="date_input">

                <%= f.label :date  %>
                <%= f.datetime_select :date, min: Date.today, :minute_step => 15 %>
            </span>	
            
            <div class="description">
                <%= f.label :description%>
                <br>
                <%= f.text_field :description, style: 'height: 10rem; width:50%;'%>
            </div>

            <%# <div class="check_box input-field"> %>
                <%# <%= f.check_box :attendees %>  
                <%# <<%= f.label "Tick if you will be attending the event." %> 
            <%# </div> %>
            
            <br>
            <div class="button">
                <%= f.submit "Create new event", class: "btn btn-primary btn-lg" %>
            </div>		
	    <% end %>	

	</div>
</div>	

</div>

app/views/events/show.html.erb
<div class="container event-details">
    <div class="row">
        <div class="col events-header">
			<h2>Events name: <%= @event.name%></h2>
		</div>
    </div>
    <div class="row">
        <div class="row row-md">
        Location: <%= @event.location %>
        </div>
        <div class="row row-md-3">
            <%if @event.creator %>
                Created by: <%= link_to @event.creator.name, @event.creator%>
            <%end%>
        </div>
        
        <div class="row row-md-3">
        Date and Time: <%= @event.date %>
        </div>
        <div class="row row-md-3">
        Description: <%= @event.description %>
        </div>

        <div class="row row-md-3 check_box input-field">
            <%= form_with(model: @event, url: event_path(@event), method: "patch") do |f| %>
                <%= f.check_box :attendees %> 
                <%= f.label "Tick if you will be attending the event." %>
                <div class="button">
                    <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
                </div>
            <% end %>
        </div>
        <div class="row row-md-3">
            <h4>Event Attendees</h4>
            <% @event.attendees.each do |p|%>
                <div class="row" id="creator-row"> 
					<p> Name: <%=p.name%></p> 
				</div> 
            <%end%> 
        </div>
    </div>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "Private Events", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? %>
              <li><%= link_to "Events", events_path %></li>
              <li><%= link_to "My Events", current_user, class: "navbar-brand"%></li> 
              <li><%= button_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>

              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Log In", user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<div class="container user-info">
	<div class="row">
		<div class="col">
			
			<h2>User Profile: <%= @current_user.name %></h2>
		</div>	
	</div>	
</div>

<div class="container">
    <div class="card card-body">
		<% if @created_events != nil%>
			<h2>Created Events</h2>
			<% @created_events.each do |event| %>
				<div class="row" id="event-row">
					<p class="event-title"><%= link_to event.name, event %></p> 
					<p>Date: <%= event.date.strftime("%d/%m/%y") %></p>
					<p>Location: <%= event.location %></p>
					<div>Description: <%= event.description %></div>
				</div>
			<% end %>
		
		<% end %>
	</div>

	<div class="card card-body">
		<% if @attended_events != nil%>
			<h2>My Event Interest</h2>
			<% @attended_events.each do |event| %>
				<div class="row" id="event-row">
					<p class="event-title"><%= link_to event.name, event %></p> 
					<p>Date: <%= event.date.strftime("%d/%m/%y") %></p>
					<p>Location: <%= event.location %></p>
					<div>Description: <%= event.description %></div>
				</div>
			<% end %>
		<% end %>
	</div>	

	<div class="card card-body">
		<% if @event != nil%>
			<h2>Created Events</h2>
			<% @events.each do |event| %>
				<div class="row" id="event-row">
					<p class="event-title"><%= link_to event.name, event %></p> 
					<p>Date: <%= event.date.strftime("%d/%m/%y") %></p>
					<p>Location: <%= event.location %></p>
					<div>Description: <%= event.description %></div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/user/show.html.erb
<div class="container user-info">
	<div class="row">
		<div class="col">
			<h2>User Profile: <%= @user.name %></h2>
		</div>	
	</div>	
</div>

<div class="container">
    <div class="card card-body">
		<% if @created_events != nil%>
			<h2>Created Events</h2>
			<% @created_events.each do |event| %>
				<div class="row border border-dark" id="event-row">
					<p class="event-title"><%= link_to event.name, event %></p> 
					<p>Date: <%= event.date.strftime("%d/%m/%y") %></p>
					<p>Location: <%= event.location %></p>
					<div>Description: <%= event.description %></div>
				</div>
			<% end %>
		
		<% end %>
	</div>

	<div class="card card-body">
		<% if @attended_events != nil%>
			<h2>My Event Interest</h2>
			<% @attended_events.each do |event| %>
				<div class="row border border-dark" id="event-row">
					<p class="event-title"><%= link_to event.name, event %></p> 
					<p>Date: <%= event.date.strftime("%d/%m/%y") %></p>
					<p>Location: <%= event.location %></p>
					<div>Description: <%= event.description %></div>
				</div>
			<% end %>
		<% end %>
	</div>	

	<div class="card card-body">
		<% if @event != nil%>
			<h2>Created Events</h2>
			<% @events.each do |event| %>
				<div class="row border border-dark" id="event-row">
					<p class="event-title"><%= link_to event.name, event %></p> 
					<p>Date: <%= event.date.strftime("%d/%m/%y") %></p>
					<p>Location: <%= event.location %></p>
					<div>Description: <%= event.description %></div>
				</div>
			<% end %>
		<% end %>
	</div>
</div>